// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cyybipewxsatzqxarohn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5eWJpcGV3eHNhdHpxeGFyb2huIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMzA4ODEsImV4cCI6MjA2MjcwNjg4MX0.dhajrcWIwBmyp8FsnmshYF1HiLh1b87cn8X7O_WtrFk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);